apiVersion: apps/v1
kind: Deployment
metadata:
  name: motor
  labels:
    app: motor
spec:
  replicas: 2
  selector:
    matchLabels:
      app: motor
  template:
    metadata:
      labels:
        app: motor
    spec:
      imagePullSecrets:
        - name: ghcr-credentials
      containers:
        - name: motor
          image: ghcr.io/juandavidturriago/mancala-motor:261d9a1da3993a245e33517c539624781bed3ccb
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: mancala-config
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests:
              cpu: "250m"
              memory: "128Mi"
            limits:
              cpu: "2000m"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: motor-svc
spec:
  selector:
    app: motor
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP
