sonar.projectKey=Juego-Mancala-con-IA-y-paralelizacion
sonar.projectName=Juego-Mancala-con-IA-y-paralelizacion
sonar.sourceEncoding=UTF-8

sonar.sources=motor/src,backend/app,frontend
sonar.tests=motor/tests,backend/tests

sonar.exclusions=**/build/**,**/__pycache__/**,**/node_modules/**,deploy/**,docs/**
