sonar.organization=juandavidturriago
sonar.projectKey=JuanDavidTurriago_Juego-Mancala-con-IA-y-paralelizacion
sonar.projectName=Juego-Mancala-con-IA-y-paralelizacion
sonar.host.url=https://sonarcloud.io
sonar.sourceEncoding=UTF-8

sonar.sources=motor/src,backend/app,frontend
sonar.tests=motor/tests,backend/tests
sonar.cfamily.compile-commands=motor/build/compile_commands.json

sonar.exclusions=**/build/**,**/__pycache__/**,**/node_modules/**,deploy/**,docs/**,**/httplib.h,**/json.hpp
