services:
  motor:
    build: ../../motor
    ports:
      - "9000:9000"
    environment:
      OMP_NUM_THREADS: "4"

  backend:
    build: ../../backend
    ports:
      - "8000:8000"
    environment:
      MOTOR_URL: "http://motor:9000"
    depends_on:
      - motor

  frontend:
    build: ../../frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

