apiVersion: apps/v1
kind: Deployment
metadata:
  name: motor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: motor
  template:
    metadata:
      labels:
        app: motor
    spec:
      containers:
        - name: motor
          image: motor:local
          ports:
            - containerPort: 9000

