apiVersion: apps/v1
kind: Deployment
metadata:
  name: motor
  labels:
    app: motor
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app: motor
  template:
    metadata:
      labels:
        app: motor
    spec:
      containers:
        - name: motor
          image: us-central1-docker.pkg.dev/mancala-kalah/mancala/mancala-motor:cd2a98f04462fded40ffc034a4c1c52f707f09f3
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: mancala-config
          startupProbe:
            httpGet:
              path: /healthz
              port: 8080
            periodSeconds: 5
            failureThreshold: 24
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              cpu: "500m"
              memory: "256Mi"
            limits:
              cpu: "2000m"
              memory: "768Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: motor
spec:
  selector:
    app: motor
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP
